CREATE TABLE IF NOT EXISTS `query` (
	`id` VARCHAR(255) NOT NULL,
    `date` VARCHAR(255),
    `system_capacity` DOUBLE,
    `module_type` INT,
    `losses` DOUBLE,
    `array_type` INT,
    `tilt` DOUBLE,
    `azimuth` DOUBLE,
    `lat` VARCHAR(255),
    `lon` VARCHAR(255),
    `pvwatts_version` VARCHAR(55),
    `ssc_version` VARCHAR(55),
    `ssc_build` VARCHAR(255),
    `ssc_module` VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS `station_info` (
	`query_id` VARCHAR(255) NOT NULL,
    `lat` VARCHAR(255),
    `lon` VARCHAR(255),
    `elev` VARCHAR(255),
    `tz` DOUBLE,
    `location` VARCHAR(255),
    `city` VARCHAR(255),
    `state` VARCHAR(255),
    `solar_resource_file` VARCHAR(255),
    `weather_data_source` VARCHAR(255),
    INDEX `queryId` (`query_id`),
    PRIMARY KEY (`query_id`),
    FOREIGN KEY (`query_id`)
		REFERENCES `query`(`id`)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `output` (
	`query_id` VARCHAR(255) NOT NULL,
    `ac_jan` VARCHAR(255),
    `ac_feb` VARCHAR(255),
    `ac_mar` VARCHAR(255),
    `ac_apr` VARCHAR(255),
    `ac_may` VARCHAR(255),
    `ac_jun` VARCHAR(255),
    `ac_jul` VARCHAR(255),
    `ac_aug` VARCHAR(255),
    `ac_sep` VARCHAR(255),
    `ac_oct` VARCHAR(255),
    `ac_nov` VARCHAR(255),
    `ac_dec` VARCHAR(255),
    `poa_jan` VARCHAR(255),
    `poa_feb` VARCHAR(255),
    `poa_mar` VARCHAR(255),
    `poa_apr` VARCHAR(255),
    `poa_may` VARCHAR(255),
    `poa_jun` VARCHAR(255),
    `poa_jul` VARCHAR(255),
    `poa_aug` VARCHAR(255),
    `poa_sep` VARCHAR(255),
    `poa_oct` VARCHAR(255),
    `poa_nov` VARCHAR(255),
    `poa_dec` VARCHAR(255),
    `solrad_jan` VARCHAR(255),
    `solrad_feb` VARCHAR(255),
    `solrad_mar` VARCHAR(255),
    `solrad_apr` VARCHAR(255),
    `solrad_may` VARCHAR(255),
    `solrad_jun` VARCHAR(255),
    `solrad_jul` VARCHAR(255),
    `solrad_aug` VARCHAR(255),
    `solrad_sep` VARCHAR(255),
    `solrad_oct` VARCHAR(255),
    `solrad_nov` VARCHAR(255),
    `solrad_dec` VARCHAR(255),
    `dc_jan` VARCHAR(255),
    `dc_feb` VARCHAR(255),
    `dc_mar` VARCHAR(255),
    `dc_apr` VARCHAR(255),
    `dc_may` VARCHAR(255),
    `dc_jun` VARCHAR(255),
    `dc_jul` VARCHAR(255),
    `dc_aug` VARCHAR(255),
    `dc_sep` VARCHAR(255),
    `dc_oct` VARCHAR(255),
    `dc_nov` VARCHAR(255),
    `dc_dec` VARCHAR(255),
    `ac_annual` VARCHAR(255),
    `solrad_annual` VARCHAR(255),
    `capacity_factor` VARCHAR(255),
    INDEX `queryId` (`query_id`),
    PRIMARY KEY (`query_id`),
    FOREIGN KEY (`query_id`)
		REFERENCES `query`(`id`)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
